#!/usr/bin/env bash
# Write apps/local/.env for air-gap compose smoke (CI or local reproduction).
#
# ADMIN_TOKEN is required by docker-compose.yml interpolation.
# MOTHERSHIP_URL / MOTHERSHIP_API_KEY / TENANT_ID are intentionally omitted
# so the node boots in air-gap mode (smoke asserts upstreamConfigured=false).
# Host binds stay on loopback — same default as the operator compose file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOKEN="${ADMIN_TOKEN:-ci-admin-$(openssl rand -hex 16)}"

cat > "$ROOT/.env" <<EOF
# Generated by scripts/ci-write-env.sh — air-gap CI compose smoke.
ADMIN_TOKEN=${TOKEN}
DATABASE_URL=postgres://skillsregistry:skillsregistry@localhost:5432/skillsregistry
NODE_ENV=production
HOST=0.0.0.0
PORT=3000
APP_BIND=127.0.0.1
POSTGRES_BIND=127.0.0.1
OLLAMA_BIND=127.0.0.1
EMBEDDER=ollama
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
LOG_LEVEL=info
LOG_FORMAT=json
EOF
